### ISSUE TITLE
Se pueden tachar ramos que no cumplen con pre-requisito

### ISSUE THREAD

**Issue by ssanchezl** [etra0/ramos#31]
Ejemplo particular de Programación y Estructuras de Datos.

Comportamiento esperado: Cuando se intente tachar Estructuras de Datos, no debería suceder nada, a menos que haya aprobado Programación.

Comportamiento actual: Aún cuando no he aprobado Programación, puedo tachar Estructuras de Datos y se desbloquean los ramos que Estructuras de Datos abre.

![screenshot from 2019-02-13 11-44-57](https://user-images.githubusercontent.com/32114641/52719964-7a44dd00-2f85-11e9-80a0-ad6def297260.png)

**Comment by etra0** [comment]
Es una feature, debido a que existen casos donde hay gente que ha tomado ramos con prerrequisitos de todas formas (incluso a mí me pasó).

**Comment by ssanchezl** [comment]
Aaaah vale man, gracias igual por responder :D
