### ISSUE TITLE
Ramos con siglas que contienen espacios no pueden aprobarse 

### ISSUE THREAD

**Issue by BooterMan98** [etra0/ramos#32]
### Si un ramo tiene una sigla espaciada (por ejemplo: "ICA 1") el ramo no puede aprobarse

Comportamietno esperado: Aprobar "**ICA 1**" al hacer click en el.

Comportamiento actual: Al hacer click en el ramo no se aprueba
![Demo del problema](https://media.giphy.com/media/Sw6IqnVZEeN4F4Azb1/giphy.gif)

Si no me equivoco la malla de ambiental e IDP tienen ramos con ese problema

**Comment by etra0** [comment]
Este comportamiento se debe a que en el momento en que se crea el bloque, la sigla es ocupada como el atributo `id` del objeto, y este por requisito de HTML no puede contener espacios. No sé qué tan necesario sea _fixear_ esto, ya que los espacios en los nombres identificadores siempre causan problemas, y usar guiones o simplemente escribirlo junto siento que no causa mayores problemas para el usuario final.

**Comment by BooterMan98** [comment]
Efectivamente no es causante de problemas al usuario final. Sin embargo, futuras funciones pueden depender de poder aprobar o no aprobar un ramo, o de la id especifica del ramo en cuestión.

**Comment by etra0** [comment]
No sé si entendí bien del todo tu comentario, pero como la sigla es ocupada por el atributo `id`, ya que por [web standard es el identificador](https://www.w3schools.com/Tags/att_global_id.asp) y este no puede contener espacios, me parece bien que siga así.

![image](https://user-images.githubusercontent.com/19335821/57733056-ef9f7700-7674-11e9-8ffb-1bd185c4ae98.png)

La otra opción que se me ocurre es que por detrás se le agrege al guión y mostrarlo normal cuando se dibuja, pero de nuevo, no trae ningún beneficio.

**Comment by BooterMan98** [comment]
Oka, yo estaba pensando en cambiar las mallas añadiéndole el guion y poner como requisito el no estar espaciadas, pues pensaba que las siglas estaban erróneamente puestas. Pero me di cuenta que en el caso de *ICA 1* la malla de ambiental tiene la sigla tal cual como esta. Voy a ver como solucionarlo, pues me trae problemas para lo que quiero agregar como *feature*.

**Comment by etra0** [comment]
Dado que no existe una convención, me parece sensato exigir un guión entre la sigla y el número. Facilita el desarrollo y hasta ahora no he recibido ninguna queja a nivel de usuarios por esto.
