### ISSUE TITLE
Curso duplicado en malla personalizada

### ISSUE THREAD

**Issue by marellanoc** [etra0/ramos#34]
Si se agrega un ramo en un semestre x y luego regreso a un semestre anterior a ese, me da la opción de volver a agregarlo y al guardar la malla el curso aparece duplicado en ambos semestres.

**Comment by BooterMan98** [comment]
Hola!
Gracias por usar la malla interactiva.  
Por cómo funciona la malla al seleccionar ramos, está se cerciora que no puedas elegir ramos ya cursados (semestres anteriores), por lo que no tendrá problemas al agregar ramos aún no cursados **en ese** semestre. Esta verificación se hace al avanzar de semestre, por lo que al generar la malla sin avanzar, no se verifica y el ramo en cuestión se duplica.

Definitivamente es un bug, lo corregiré en cuanto tenga tiempo. Mientras tanto, como workaround antes de generar la malla avanza al siguiente semestre y luego generala.

---
La próxima vez que detalles un problema, trata de poner la mayor cantidad de detalles posibles, cómo la función que estabas utilizando, la malla, entre otras cosas. Así se podrá identificar la causa del problema de una manera mas eficaz.

Saludos!
