### ISSUE TITLE
Archivo duplicado

### ISSUE THREAD

**Issue by DmACKGL** [etra0/ramos#41]
Hola!

Personalizar y Prioridad tienen archivos duplicados (selectableRamo.js) los cuales tienen pocas diferencias unos de otros.

Seria buena idea revisar el archivo mas completo para así dejar uno solo y mantener mejor orden.
![image](https://user-images.githubusercontent.com/10565361/65634188-14f1a980-dfb4-11e9-88da-d6a7cd1a8e10.png)
[DiffChecker](https://www.diffchecker.com/pDLrxZ3W)

**Comment by BooterMan98** [comment]
Hola! Aunque de momento no tengan muchas diferencias, puede que en un futuro los haga más distintos dependiendo de lo que agregue. Pero por ahora esperare a que ocurran los pull request y de ahí los junte en un archivo mientras tanto y mejorar el orden.
