### ISSUE TITLE
No se deseleccionan ramos luegos de pasarlos en la calculadora de prioridad

### ISSUE THREAD

**Issue by vix35** [etra0/ramos#46]
En un semestre (digámosle semestre 1) reprobé 2 ramos, por lo tanto se mantienen en el siguiente(semestre 2), ya que hay que darlos inmediatamente(hasta aquí todo bien), el tema es que en el semestre 2 obtengo nota suficiente para pasarlos, pero estos ramos se mantienen en el semestre 3.
Adjunto imágenes ilustrativas.
![3](https://user-images.githubusercontent.com/26469760/75832329-c0d5c700-5d94-11ea-9e87-140a64b677a7.png)
![2](https://user-images.githubusercontent.com/26469760/75832353-c8956b80-5d94-11ea-9b67-e2f67ad7735a.png)
![1](https://user-images.githubusercontent.com/26469760/75832358-caf7c580-5d94-11ea-8002-5f9c4346f7b4.png)

**Comment by etra0** [comment]
@CsarMan

**Comment by BooterMan98** [comment]
Noted. De paso, te sugiero que leas [esto](https://github.com/etra0/ramos/pull/42)

**Comment by vix35** [comment]
ohh dale gracias
